version: '3'

services:
  php:
    build: .
    working_dir: /application
    volumes:
    - .:/application
    ports:
      - 80:8080
    network_mode: bridge
  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=root123
    - MYSQL_DATABASE=sylius
    - MYSQL_USER=user
    - MYSQL_PASSWORD=secret
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
    - "3306:3306"
    network_mode: bridge
volumes:
  plugin_db:

networks:
  default:
    external:
      name: bridge